nome_cliente = input("Nome do cliente: ")
equipamento = input("Equipamento: ")
defeito = input("Defeito: ")
técnico = input("Técnico responsável: ")
data_entrada = input("Data de entrada (dd/mm/aaaa): ")
prioridade = input("Prioridade (Alta/Média/Baixa): ")
status = input("Status (Em aberta/Concluído/Aguardando peças): ")

print("Ordem de Serviço:")
print(f"Cliente: {nome_cliente}")
print(f"Equipamento: {equipamento}")
print(f"Defeito informado: {defeito}")
print(f"Técnico responsável: {técnico}")
print(f"Data de entrada: {data_entrada}")
print(f"Prioridade: {prioridade}")
print(f"Status: {status}")