def mostrar_menu():
    print("\n=== Sistema de Equipamentos ===")
    print("1 - Cadastrar equipamento")
    print("2 - Listar todos")
    print("3 - Buscar por marca")
    print("4 - Buscar por cliente")
    print("5 - Mostrar total de cadastros")
    print("6 - Editar cadastro")
    print("7 - Remover cadastro")
    print("0 - Sair")
